const papers=[
['01','BIOLOGY','Postprandial Cognition Among High School Adolescents','An original student study examining cognition, nutrition and measurable academic-performance signals among adolescents.','Samiksha Shivkumar','https://drive.google.com/file/d/16sSfHNwnKGUaZdEY-xCaGWxawqaEJaEg/view?usp=sharing','https://i.pinimg.com/1200x/0b/e1/ed/0be1edaad55616a0cb3af59fcbc92b1d.jpg'],
['02','COMPUTER SCIENCE','Using Machine Learning to Accelerate Quantum Dot Production for Next-Generation Green Technology','A technical investigation into how machine learning can accelerate materials research and quantum-dot production for greener technologies.','Jhala Hraday, Ankit Rathi, Xie Yundi','https://drive.google.com/file/d/1Cldih94vcYc9n6Kly3nrYeYvafuFZ3xH/view','https://i.pinimg.com/736x/5e/83/30/5e8330b79fad9710749f296c6925ba30.jpg'],
['03','FINANCE','The Relationship Between Financial Literacy, Delayed Gratification, and Career Resilience','A student-led analysis of how financial literacy and decision-making habits relate to long-term career resilience.','Jacklin Wang, Woocheol Jeong','https://drive.google.com/file/d/1DVNeqpjL0K2hNd10umboCF-y3zuVUudX/view','https://i.pinimg.com/1200x/3a/e5/d4/3ae5d49b6a5d012e226d8f4ca65a21e3.jpg'],
['04','MATHEMATICS','Validating Mathematical Modeling for Genetic Switch Analysis','A modelling-focused paper testing how mathematical frameworks can support the analysis of biological genetic switches.','Alicia Chan, Maha Essadi, Rohan Chhaya, Saraswati Sridhar','https://docs.google.com/document/d/1PeUrb1ORmBE99-bMZfvb0AYsQJUZYSMm/edit?tab=t.0','https://i.pinimg.com/736x/bd/ba/13/bdba13c7f3cce5c5c9f189f574ff4cda.jpg'],
['05','TECHNOLOGY','Social Media Privacy and Informed Consent in the Digital Age','A policy and ethics paper examining consent, privacy, data collection and platform responsibility in digital environments.','Samantha Alvarez','https://drive.google.com/file/d/1Eqgr1yXOygil7iYgQeazRUMYGouWOOmD/view','https://i.pinimg.com/736x/b1/b8/83/b1b88379ca10ca8d912807d2c32ca0a3.jpg'],
['06','INTERNATIONAL RELATIONS','The Shift in Arab American Demands for Legal Representation','A historical and social analysis of changing demands for legal representation across Arab American communities.','Zachary Samuel Rodger','https://drive.google.com/file/d/1fGH9UFGGq1YY7XTmVb-KKnohK_H1-Q1H/view','https://i.pinimg.com/1200x/8e/92/fb/8e92fb0a655c5b057f258df68ee26d5f.jpg']
];
const articles=[
['MENTAL HEALTH','Stress Edition: Short-Term vs Long-Term Stress in Adolescents','Annabelle Tiffany Sophia Hartono','A comparison of acute and chronic stress, their different triggers, effects and practical ways adolescents can manage them.','https://medium.com/@technology.gseo/stress-edition-short-term-vs-long-term-stress-in-adolescents-c0a690426409'],
['ECONOMICS','The Invisible Hand','Najwa Dida Al Wafiy','An accessible introduction to Adam Smith’s invisible hand, market coordination and the limits of unregulated markets.','https://medium.com/@technology.gseo/the-invisible-hand-aa14f27bbcce'],
['MATHEMATICS','From Chunks to Precision: Finding Smaller Turbulence Paths','Michael Sutanto','How mathematical modelling and data assimilation can improve predictions of chaotic turbulence in engineering systems.','https://medium.com/@technology.gseo/from-chunks-to-precision-how-we-can-use-math-to-find-smaller-turbulence-paths-e16a502eae4b'],
['FINANCE','The Mechanics of “Gorengan” Stocks on the IDX','Logan Alvaro Goh','A breakdown of low liquidity, wash trading, pump-and-dump cycles and regulatory warning signs in Indonesian equities.','https://medium.com/@technology.gseo/the-mechanics-of-gorengan-stocks-how-price-manipulation-works-on-the-idx-f758b7bb62a8'],
['BIOLOGY','How AI Is Transforming Protein Structure Prediction','Aisha Kaka Al Wafiy','How systems such as AlphaFold predict three-dimensional protein structures and accelerate biological and drug-discovery research.','https://medium.com/@technology.gseo/how-artificial-intelligence-is-transforming-protein-structure-prediction-and-protein-interaction-af0e16c92105'],
['CHEMISTRY','Calcium-Ion Batteries Will Replace Lithium-Ion Batteries','Nicholas Raven Wibowo','A look at new quasi-solid-state electrolytes that could make calcium-ion batteries more stable, scalable and sustainable.','https://medium.com/@technology.gseo/calcium-ion-batteries-will-replace-lithium-ion-batteries-334fbe2f3eef'],
['PHYSICS','Microscopy with Quantum Mechanics','Michael Sutanto','Exploring quantum electron microscopy, photon entanglement, tunnelling and lower-radiation approaches to biological imaging.','https://medium.com/@technology.gseo/microscopy-with-quantum-mechanics-541fae38d9e6'],
['ASTRONOMY','“Artificial” Cosmic Dust and the Origins of Life','Angelina Jonly Welirang','How laboratory-created cosmic dust supports the possibility that life-forming chemistry began in space before reaching Earth.','https://medium.com/@technology.gseo/artificial-cosmic-dust-brings-scientists-closer-to-lifes-origins-10a14c236dc1'],
['ENGINEERING','Fluid Gears: A New System for Rotational Motion','Josh Bennett Kusuma','A contactless gear mechanism that transfers rotational motion through fluid flow, reducing friction, wear and maintenance.','https://medium.com/@technology.gseo/fluid-gears-a-new-mechanical-system-for-rotational-motion-6684f03eec5d']
];
const interviews=[
['UPenn: Business Economics & Public Policy','Katherine Yusuf','https://youtu.be/RDitsFPltjw','RDitsFPltjw','Katherine shares an honest perspective on university life at Penn, the transition into a demanding academic environment and the choices that shaped her path.',''],
['UT Austin: CS + Business','Shashank Ganta','https://youtu.be/2dAScZl5j98','2dAScZl5j98','Shashank discusses studying at UT Austin, finding opportunities beyond the classroom and building a balanced, purposeful university experience.',''],
['Yale University: Ethnicity, Race, and Migration','Samantha Alvarez','https://youtu.be/uFreiWHk2oQ','uFreiWHk2oQ','Samantha reflects on Yale academics, campus culture and the habits that helped her navigate admissions and make the most of university life.',''],
['NYU: Business and AI','Peter Ma','https://youtu.be/O1er-F2HHoo','O1er-F2HHoo','Peter explores the pace and independence of studying at NYU, with practical insight into academics, community and learning in New York City.',''],
['UPenn: Economics','Zachary Rodger','https://youtu.be/fRcHhOLeWd8','fRcHhOLeWd8','Zachary offers a second perspective on Penn, discussing intellectual growth, student opportunities and the decisions behind an ambitious academic journey.',''],
['NUS: Mathematics','Thang Pang Ern','https://www.youtube.com/watch?v=W2G3wgOVVDg','W2G3wgOVVDg','Pang Ern explains how top mathematicians think, learn and approach research while sharing his experience as a Mathematics student at the National University of Singapore.',''],

];
const teams={
  Leadership:[['Kartik Nayak','President','public/images/team-kartik.png'],['Aisha Kaka','Vice President','public/images/team-aisha.png']],
  Academic:[['Aisha Kaka Al-Wafiy','Head of Biology','public/images/team-aisha.png'], ['Nicholas Raven Wibowo','Head of Chemistry','public/images/team-raven.png'],['Josh Bennett Kusuma','Head of Physics','public/images/team-josh.png'],['Najwa Dida Al-Wafiy','Head of Economics','public/images/team-dida.png'],['Logan Alvaro Goh','Head of Finance','public/images/team-logan.png'],['Angelina Jonly Welirang','Physics',''],['Michael Sutanto','Physics',''],['Annabelle Tiffany Sophia Hartono','Mental Health','']],
  Content:[['Profile coming soon','Writer',''],['Profile coming soon','Interviewer',''],['Profile coming soon','Newsletter Member',''],['Profile coming soon','Video Content Member','']],
  Growth:[['Profile coming soon','Marketing Member',''],['Profile coming soon','Outreach Member',''],['Profile coming soon','Ambassador Member',''],['Profile coming soon','Partnerships Member','']],
  Technology:[['Profile coming soon','Website Member',''],['Profile coming soon','Data and Analytics Member',''],['Profile coming soon','Technical Support Member','']],
  Ambassadors:[['Profile coming soon','Student Ambassador',''],['Profile coming soon','Student Ambassador',''],['Profile coming soon','Student Ambassador',''],['Profile coming soon','Student Ambassador','']]
};
document.querySelector('#paper-grid').innerHTML=papers.map(p=>`<a class="paper reveal" href="${p[5]}" target="_blank" rel="noreferrer"><img src="${p[6]}" alt="Student research"><span class="paper-meta">${p[0]} / ${p[1]} ↗</span><div><h3>${p[2]}</h3><p class="paper-summary">${p[3]}</p><p class="paper-author">AUTHORS<br>${p[4]}</p></div></a>`).join('');
document.querySelector('#article-list').innerHTML=articles.map((a,i)=>`<a class="article reveal" href="${a[4]}" target="_blank" rel="noreferrer"><span>${String(i+1).padStart(2,'0')}</span><div><small>${a[0]}</small><h3>${a[1]}</h3><p>${a[3]}</p><span class="author">BY ${a[2]}</span></div><span>↗</span></a>`).join('');
document.querySelector('#interview-grid').innerHTML=interviews.map(i=>`<a class="interview reveal" href="${i[2]}" target="_blank" rel="noreferrer"><small>GSEO INTERVIEW ↗</small><div class="interview-preview">${i[3]?`<img src="https://img.youtube.com/vi/${i[3]}/hqdefault.jpg" alt="Preview of ${i[0]} interview"><span class="play-button">▶</span>`:`<div class="university-wordmark">GSEO</div>`}${i[5]?`<span class="interview-university-logo"><img src="${i[5]}" alt="National University of Singapore logo"></span>`:''}</div><h3>${i[0]}</h3><p class="interview-person">A conversation with ${i[1]}.</p><p class="interview-description">${i[4]}</p><span class="watch-link">Watch interview ↗</span></a>`).join('');
const tabs=document.querySelector('.team-tabs'),directory=document.querySelector('.team-directory');
tabs.innerHTML=Object.keys(teams).map((name,index)=>`<button class="team-tab ${index===0?'active':''}" data-team="${name}">${name}</button>`).join('');
function showTeam(name){directory.innerHTML=teams[name].map(member=>`<article class="team-card">${member[2]?`<img src="${member[2]}" alt="${member[0]}">`:`<div class="team-placeholder"><img src="public/images/gseo-simple-logo-transparent.png" alt=""></div>`}<h3>${member[0]}</h3><p>${member[1]}</p></article>`).join('');tabs.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.team===name))}
tabs.addEventListener('click',event=>{if(event.target.dataset.team)showTeam(event.target.dataset.team)});showTeam('Leadership');
const menuButton=document.querySelector('.menu-button'),menu=document.querySelector('.mobile-menu');menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',open);menu.setAttribute('aria-hidden',!open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menuButton.click()));
addEventListener('scroll',()=>document.querySelector('#nav').classList.toggle('scrolled',scrollY>40),{passive:true});
const heroFrames=document.querySelectorAll('.hero-frame'),campusName=document.querySelector('.campus-name'),campusProgress=document.querySelector('.campus-progress');let heroIndex=0;setInterval(()=>{heroFrames[heroIndex].classList.remove('active');heroIndex=(heroIndex+1)%heroFrames.length;heroFrames[heroIndex].classList.add('active');campusName.textContent=heroFrames[heroIndex].dataset.campus;campusProgress.textContent=`${String(heroIndex+1).padStart(2,'0')} / ${String(heroFrames.length).padStart(2,'0')}`},5000);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
